name: lot
version: 0.0.1
publish_to: none
environment:
  sdk: ^3.7.0
description: A new Flutter project.
dependencies:
  auto_route: ^10.0.1
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  injectable: ^2.5.0
  package_info_plus: ^8.3.0
dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  pubspec_dependency_sorter: ^1.0.5
flutter:
  uses-material-design: true
  fonts:
    - family: Boldonse
      fonts:
        - asset: 'assets/fonts/Boldonse-Regular.ttf'
  assets:
    - 'assets/fonts/Boldonse-Regular.ttf'